// Code generated by sql_update_by_struct DO NOT EDIT.

package testdata

func (p *PersonUpdate) Update() ([]string, []any) {
	cols := make([]string, 0, 3)
	vals := make([]any, 0, 3)
	var index = 1
	if p.Name != nil {
		vals = append(vals, *p.Name)
		cols = append(cols, "name=$1")
		index++
	}
	if p.Age != nil {
		vals = append(vals, *p.Age)
		cols = append(cols, "age=$2")
		index++
	}
	if p.Email != nil {
		vals = append(vals, *p.Email)
		cols = append(cols, "email=$3")
		index++
	}
	return cols, vals
}
